/* Generated by Yosys 0.9+3621 (git sha1 84e9fa7, gcc 8.3.1 -fPIC -Os) */

module chip_io(GPIO_0, GPIO_1, GPIO_2, GPIO_3, B_0_pll, B_1_pll, B_2_pll, B_3_pll, REF_CLK, REF_CLK_pll, CLK, CLK_pll, VCO_IN, VCO_IN_pll, EN_CP, EN_CP_pll, EN_VCO, EN_VCO_pll, B_CP, B_CP_pll, B_VCO, B_VCO_pll, VDDA2, VSSA, VDDD2, VSSD, VDDR, GNDR, VDDO, GNDO, PORB);
  output B_0_pll;
  output B_1_pll;
  output B_2_pll;
  output B_3_pll;
  output B_CP;
  input B_CP_pll;
  output B_VCO;
  input B_VCO_pll;
  output CLK;
  input CLK_pll;
  input EN_CP;
  output EN_CP_pll;
  input EN_VCO;
  output EN_VCO_pll;
  input GNDO;
  wire GNDO_pll;
  input GNDR;
  wire GNDR_pll;
  input GPIO_0;
  input GPIO_1;
  input GPIO_2;
  input GPIO_3;
  input PORB;
  input REF_CLK;
  output REF_CLK_pll;
  wire TIE_HI_ESD;
  wire TIE_LO_ESD;
  wire VCCD1;
  input VCO_IN;
  output VCO_IN_pll;
  wire VDDA;
  wire VDDA1;
  input VDDA2;
  wire VDDA_pll;
  wire VDDD;
  input VDDD2;
  wire VDDD_pll;
  wire VDDIO;
  input VDDO;
  wire VDDO_pll;
  input VDDR;
  wire VDDR_pll;
  input VSSA;
  wire VSSA1;
  wire VSSA_pll;
  input VSSD;
  wire VSSD1;
  wire VSSD_pll;
  wire VSSIO;
  sky130_fd_io__top_gpiov2 B_CP_PAD (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .ANALOG_EN(VSSD1),
    .ANALOG_POL(VSSD1),
    .ANALOG_SEL(VSSD1),
    .DM({ VCCD1, VCCD1, VSSD1 }),
    .ENABLE_H(PORB),
    .ENABLE_INP_H(TIE_LO_ESD),
    .ENABLE_VDDA_H(GNDO_pll),
    .ENABLE_VDDIO(VCCD1),
    .ENABLE_VSWITCH_H(GNDO_pll),
    .HLD_H_N(VDDIO),
    .HLD_OVR(VSSD1),
    .IB_MODE_SEL(VSSD1),
    .IN(),
    .INP_DIS(VSSD1),
    .IN_H(),
    .OE_N(VSSD1),
    .OUT(B_CP_pll),
    .PAD(B_CP),
    .PAD_A_ESD_0_H(),
    .PAD_A_ESD_1_H(),
    .PAD_A_NOESD_H(),
    .SLOW(VSSD1),
    .TIE_HI_ESD(TIE_HI_ESD),
    .TIE_LO_ESD(TIE_LO_ESD),
    .VTRIP_SEL(VSSD1)
  );
  sky130_fd_io__top_gpiov2 B_VCO_PAD (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .ANALOG_EN(VSSD1),
    .ANALOG_POL(VSSD1),
    .ANALOG_SEL(VSSD1),
    .DM({ VCCD1, VCCD1, VSSD1 }),
    .ENABLE_H(PORB),
    .ENABLE_INP_H(TIE_LO_ESD),
    .ENABLE_VDDA_H(GNDO_pll),
    .ENABLE_VDDIO(VCCD1),
    .ENABLE_VSWITCH_H(GNDO_pll),
    .HLD_H_N(VDDIO),
    .HLD_OVR(VSSD1),
    .IB_MODE_SEL(VSSD1),
    .IN(),
    .INP_DIS(VSSD1),
    .IN_H(),
    .OE_N(VSSD1),
    .OUT(B_VCO_pll),
    .PAD(B_VCO),
    .PAD_A_ESD_0_H(),
    .PAD_A_ESD_1_H(),
    .PAD_A_NOESD_H(),
    .SLOW(VSSD1),
    .TIE_HI_ESD(TIE_HI_ESD),
    .TIE_LO_ESD(TIE_LO_ESD),
    .VTRIP_SEL(VSSD1)
  );
  sky130_fd_io__top_power_lvc_wpad CLK_PAD (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .P_PAD(CLK)
  );
  sky130_fd_io__top_gpiov2 EN_CP_PAD (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .ANALOG_EN(VSSD1),
    .ANALOG_POL(VSSD1),
    .ANALOG_SEL(VSSD1),
    .DM({ VSSD1, VSSD1, VCCD1 }),
    .ENABLE_H(PORB),
    .ENABLE_INP_H(TIE_LO_ESD),
    .ENABLE_VDDA_H(GNDO_pll),
    .ENABLE_VDDIO(VCCD1),
    .ENABLE_VSWITCH_H(GNDO_pll),
    .HLD_H_N(VDDIO),
    .HLD_OVR(VSSD1),
    .IB_MODE_SEL(VSSD1),
    .IN(EN_CP_pll),
    .INP_DIS(VSSD1),
    .IN_H(),
    .OE_N(VCCD1),
    .OUT(VSSD1),
    .PAD(EN_CP),
    .PAD_A_ESD_0_H(),
    .PAD_A_ESD_1_H(),
    .PAD_A_NOESD_H(),
    .SLOW(VSSD1),
    .TIE_HI_ESD(TIE_HI_ESD),
    .TIE_LO_ESD(TIE_LO_ESD),
    .VTRIP_SEL(VSSD1)
  );
  sky130_fd_io__top_gpiov2 EN_VCO_PAD (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .ANALOG_EN(VSSD1),
    .ANALOG_POL(VSSD1),
    .ANALOG_SEL(VSSD1),
    .DM({ VSSD1, VSSD1, VCCD1 }),
    .ENABLE_H(PORB),
    .ENABLE_INP_H(TIE_LO_ESD),
    .ENABLE_VDDA_H(GNDO_pll),
    .ENABLE_VDDIO(VCCD1),
    .ENABLE_VSWITCH_H(GNDO_pll),
    .HLD_H_N(VDDIO),
    .HLD_OVR(VSSD1),
    .IB_MODE_SEL(VSSD1),
    .IN(EN_VCO_pll),
    .INP_DIS(VSSD1),
    .IN_H(),
    .OE_N(VCCD1),
    .OUT(VSSD1),
    .PAD(EN_VCO),
    .PAD_A_ESD_0_H(),
    .PAD_A_ESD_1_H(),
    .PAD_A_NOESD_H(),
    .SLOW(VSSD1),
    .TIE_HI_ESD(TIE_HI_ESD),
    .TIE_LO_ESD(TIE_LO_ESD),
    .VTRIP_SEL(VSSD1)
  );
  sky130_fd_io__top_ground_hvc_wpad GNDO_PAD (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .G_PAD(GNDO)
  );
  sky130_fd_io__top_ground_hvc_wpad GNDR_PAD (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .G_PAD(GNDR)
  );
  sky130_fd_io__top_gpiov2 GPIO_0_PAD (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .ANALOG_EN(VSSD1),
    .ANALOG_POL(VSSD1),
    .ANALOG_SEL(VSSD1),
    .DM({ VSSD1, VSSD1, VCCD1 }),
    .ENABLE_H(PORB),
    .ENABLE_INP_H(TIE_LO_ESD),
    .ENABLE_VDDA_H(GNDO_pll),
    .ENABLE_VDDIO(VCCD1),
    .ENABLE_VSWITCH_H(GNDO_pll),
    .HLD_H_N(VDDIO),
    .HLD_OVR(VSSD1),
    .IB_MODE_SEL(VSSD1),
    .IN(B_0_pll),
    .INP_DIS(VSSD1),
    .IN_H(),
    .OE_N(VCCD1),
    .OUT(VSSD1),
    .PAD(GPIO_0),
    .PAD_A_ESD_0_H(),
    .PAD_A_ESD_1_H(),
    .PAD_A_NOESD_H(),
    .SLOW(VSSD1),
    .TIE_HI_ESD(TIE_HI_ESD),
    .TIE_LO_ESD(TIE_LO_ESD),
    .VTRIP_SEL(VSSD1)
  );
  sky130_fd_io__top_gpiov2 GPIO_1_PAD (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .ANALOG_EN(VSSD1),
    .ANALOG_POL(VSSD1),
    .ANALOG_SEL(VSSD1),
    .DM({ VSSD1, VSSD1, VCCD1 }),
    .ENABLE_H(PORB),
    .ENABLE_INP_H(TIE_LO_ESD),
    .ENABLE_VDDA_H(GNDO_pll),
    .ENABLE_VDDIO(VCCD1),
    .ENABLE_VSWITCH_H(GNDO_pll),
    .HLD_H_N(VDDIO),
    .HLD_OVR(VSSD1),
    .IB_MODE_SEL(VSSD1),
    .IN(B_1_pll),
    .INP_DIS(VSSD1),
    .IN_H(),
    .OE_N(VCCD1),
    .OUT(VSSD1),
    .PAD(GPIO_1),
    .PAD_A_ESD_0_H(),
    .PAD_A_ESD_1_H(),
    .PAD_A_NOESD_H(),
    .SLOW(VSSD1),
    .TIE_HI_ESD(TIE_HI_ESD),
    .TIE_LO_ESD(TIE_LO_ESD),
    .VTRIP_SEL(VSSD1)
  );
  sky130_fd_io__top_gpiov2 GPIO_2_PAD (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .ANALOG_EN(VSSD1),
    .ANALOG_POL(VSSD1),
    .ANALOG_SEL(VSSD1),
    .DM({ VSSD1, VSSD1, VCCD1 }),
    .ENABLE_H(PORB),
    .ENABLE_INP_H(TIE_LO_ESD),
    .ENABLE_VDDA_H(GNDO_pll),
    .ENABLE_VDDIO(VCCD1),
    .ENABLE_VSWITCH_H(GNDO_pll),
    .HLD_H_N(VDDIO),
    .HLD_OVR(VSSD1),
    .IB_MODE_SEL(VSSD1),
    .IN(B_2_pll),
    .INP_DIS(VSSD1),
    .IN_H(),
    .OE_N(VCCD1),
    .OUT(VSSD1),
    .PAD(GPIO_2),
    .PAD_A_ESD_0_H(),
    .PAD_A_ESD_1_H(),
    .PAD_A_NOESD_H(),
    .SLOW(VSSD1),
    .TIE_HI_ESD(TIE_HI_ESD),
    .TIE_LO_ESD(TIE_LO_ESD),
    .VTRIP_SEL(VSSD1)
  );
  sky130_fd_io__top_gpiov2 GPIO_3_PAD (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .ANALOG_EN(VSSD1),
    .ANALOG_POL(VSSD1),
    .ANALOG_SEL(VSSD1),
    .DM({ VSSD1, VSSD1, VCCD1 }),
    .ENABLE_H(PORB),
    .ENABLE_INP_H(TIE_LO_ESD),
    .ENABLE_VDDA_H(GNDO_pll),
    .ENABLE_VDDIO(VCCD1),
    .ENABLE_VSWITCH_H(GNDO_pll),
    .HLD_H_N(VDDIO),
    .HLD_OVR(VSSD1),
    .IB_MODE_SEL(VSSD1),
    .IN(B_3_pll),
    .INP_DIS(VSSD1),
    .IN_H(),
    .OE_N(VCCD1),
    .OUT(VSSD1),
    .PAD(GPIO_3),
    .PAD_A_ESD_0_H(),
    .PAD_A_ESD_1_H(),
    .PAD_A_NOESD_H(),
    .SLOW(VSSD1),
    .TIE_HI_ESD(TIE_HI_ESD),
    .TIE_LO_ESD(TIE_LO_ESD),
    .VTRIP_SEL(VSSD1)
  );
  sky130_fd_io__top_power_lvc_wpad REF_CLK_PAD (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .P_PAD(REF_CLK)
  );
  sky130_fd_io__top_power_lvc_wpad VCO_IN_PAD (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .P_PAD(VCO_IN)
  );
  sky130_fd_io__top_power_lvc_wpad VDDA_PAD (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .P_PAD(VDDA)
  );
  sky130_fd_io__top_power_lvc_wpad VDDD_PAD (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .P_PAD(VDDD)
  );
  sky130_fd_io__top_power_hvc_wpadv2 VDDO_PAD (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .P_PAD(VDDO)
  );
  sky130_fd_io__top_power_hvc_wpadv2 VDDR_PAD (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .P_PAD(VDDR)
  );
  sky130_fd_io__top_ground_lvc_wpad VSSA_PAD (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .G_PAD(VSSA)
  );
  sky130_fd_io__top_ground_lvc_wpad VSSD_PAD (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .G_PAD(VSSD)
  );
  sky130_ef_io__corner_pad corner_1 (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .VCCD(VCCD1),
    .VCCHIB(VCCD1),
    .VDDA(VDDA1),
    .VDDIO(VDDIO),
    .VDDIO_Q(),
    .VSSA(GNDO_pll),
    .VSSD(VSSD1),
    .VSSIO(GNDR_pll),
    .VSSIO_Q(),
    .VSWITCH(VDDIO)
  );
  sky130_ef_io__corner_pad corner_2 (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .VCCD(VCCD1),
    .VCCHIB(VCCD1),
    .VDDA(VDDA1),
    .VDDIO(VDDIO),
    .VDDIO_Q(),
    .VSSA(GNDO_pll),
    .VSSD(VSSD1),
    .VSSIO(GNDR_pll),
    .VSSIO_Q(),
    .VSWITCH(VDDIO)
  );
  sky130_ef_io__corner_pad corner_3 (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .VCCD(VCCD1),
    .VCCHIB(VCCD1),
    .VDDA(VDDA1),
    .VDDIO(VDDIO),
    .VDDIO_Q(),
    .VSSA(GNDO_pll),
    .VSSD(VSSD1),
    .VSSIO(GNDR_pll),
    .VSSIO_Q(),
    .VSWITCH(VDDIO)
  );
  sky130_ef_io__corner_pad corner_4 (
    .AMUXBUS_A(),
    .AMUXBUS_B(),
    .VCCD(VCCD1),
    .VCCHIB(VCCD1),
    .VDDA(VDDA1),
    .VDDIO(VDDIO),
    .VDDIO_Q(),
    .VSSA(GNDO_pll),
    .VSSD(VSSD1),
    .VSSIO(GNDR_pll),
    .VSSIO_Q(),
    .VSWITCH(VDDIO)
  );
  assign VDDO_pll = VDDA1;
  assign VDDR_pll = VDDIO;
  assign VDDD_pll = VCCD1;
  assign VSSD_pll = VSSD1;
  assign VSSA1 = GNDO_pll;
  assign VSSIO = GNDR_pll;
endmodule
